name: Build app

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build FunManipulator --no-restore
    - name: Publish
      run: dotnet publish FunManipulator -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true --output app_win_x64
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: FunManipulator_win_x64
        path: app_win_x64
    - name: Publish self-contained
      run: dotnet publish FunManipulator -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true --output app_win_x64_selfcontained
    - name: Upload self-contained
      uses: actions/upload-artifact@v2
      with:
        name: FunManipulator_win_x64_selfcontained
        path: app_win_x64_selfcontained